# Generated by Django 6.0.1 on 2026-01-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complaint_confirmed_at_complaint_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
