# Generated by Django 6.0.1 on 2026-07-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_complaint_assigned_to_complaint_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('hostel_office', 'Hostel Office'), ('warden', 'Hostel Warden'), ('hmc', 'Hostel Management Committee')], default='student', max_length=20),
        ),
    ]
