# Generated by Django 6.0.1 on 2026-07-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_complaint_complaint_number_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_number',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
