# Generated by Django 6.0.1 on 2026-07-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_complaint_complaint_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='hmc_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='warden_remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated_warden', 'Escalated to Warden'), ('escalated_hmc', 'Escalated to HMC')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated_warden', 'Escalated to Warden'), ('escalated_hmc', 'Escalated to HMC')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['user', 'status'], name='core_compla_user_id_d6d24b_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['assigned_to'], name='core_compla_assigne_4f1dde_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['complaint_number'], name='core_compla_complai_e20907_idx'),
        ),
    ]
